defaults:
  - _self_
  - data: esc50
  - model: esc50-cnn
  - training: base2
  #- training: kaggle-T4

test:
  reproducible: false
  experiment_path: ../../../outputs/train_crossval/007
  checkpoints:
    - 'terminal.pt'
    #- 'best_val_loss.pt'

data:
  use_hardcoded_global_stats: true
  hardcoded_global_stats:
    - [-55.599957,  21.008253]
    - [-55.503323,  21.025076]
    - [-55.373093,  21.019352]
    - [-55.464325,  20.95555 ]
    - [-55.449673,  21.124916]


hydra:
  run:
    dir: outputs/${hydra:job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true  # Force working directory change
  #job_logging:
    #disable_existing_loggers: true