defaults:
  - _self_
  - data: esc50
  - model: esc50-cnn
  - training: base2
  #- training: kaggle-T4

test:
  reproducible: false
  experiment_path: ../../../results/sample-run
  checkpoints:
    - 'terminal.pt'
    #- 'best_val_loss.pt'

data:
  use_hardcoded_global_stats: true
  hardcoded_global_stats:
    - [-42.994774,  28.871056]
    - [-43.076977,  28.749863]
    - [-42.75472 ,  28.80137 ]
    - [-42.946777,  28.738012]
    - [-42.961735,  28.822393]


hydra:
  run:
    dir: outputs/${hydra:job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true  # Force working directory change
  #job_logging:
    #disable_existing_loggers: true