defaults:
  - _self_
  - data: esc50
  - model: audio-mlp
  - training: base  
  #- training: kaggle-T4

test:
  reproducible: false
  experiment_path: ../../../results/sample-run
  checkpoints:
    - 'terminal.pt'
    #- 'best_val_loss.pt'

data:
  use_hardcoded_global_stats: true
  hardcoded_global_stats:
    - [-54.369884, 20.843649]
    - [-54.27712, 20.85503]
    - [-54.188335, 20.79954]
    - [-54.236378, 20.792656]
    - [-54.193005, 20.953829]


hydra:
  run:
    dir: outputs/${hydra:job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true  # Force working directory change
  #job_logging:
    #disable_existing_loggers: true