device_id: 0
epochs: 200
patience: 20


# DataLoader
batch_size: 32
#num_workers: 2  # 6-16 for Linux
num_workers: 0
#persistent_workers: true
persistent_workers: false
disable_bat_pbar: false


# Optimization
lr: 0.001
weight_decay: 0.001
warm_epochs: 10
gamma: 0.8
step_size: 5
